package io.equitrack.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.time.LocalDateTime;

/**
 * Data Transfer Object for category information
 * Used to transfer category data between frontend and backend
 */
@Data                    // Lombok: Auto-generates getters, setters, toString, equals, hashCode
@AllArgsConstructor      // Lombok: Creates constructor with all fields as parameters
@NoArgsConstructor       // Lombok: Creates empty constructor (required for JSON deserialization)
@Builder                 // Lombok: Enables builder pattern for object creation
public class CategoryDTO {

    // Database unique identifier - auto-generated by JPA
    private Long id;

    // Links this category to specific user - ensures data isolation
    private Long profileId;

    // Category display name (e.g., "Food", "Transport", "Salary")
    private String name;

    // Visual icon representation (emoji or icon class)
    private String icon;

    // Category type: "income" (money in) or "expense" (money out)
    private String type;

    // Timestamp when category was created (auto-set by system)
    private LocalDateTime createdAt;

    // Timestamp when category was last modified (auto-updated)
    private LocalDateTime updatedAt;
}