package io.equitrack.dto;

import lombok.AllArgsConstructor;    // Lombok: Generates constructor with all fields
import lombok.Builder;              // Lombok: Enables builder pattern for object creation
import lombok.Data;                 // Lombok: Auto-generates getters, setters, toString, equals, hashCode
import lombok.NoArgsConstructor;    // Lombok: Generates empty constructor for JSON deserialization

import java.math.BigDecimal;        // Precise decimal numbers for monetary values
import java.time.LocalDate;         // Date without time (for expense date)
import java.time.LocalDateTime;     // Date with time (for audit timestamps)

/**
 * Data Transfer Object for expense transactions
 * Represents money outflow operations in the financial system
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class ExpenseDTO {

    // Unique database identifier - auto-generated by JPA
    private Long id;

    // Expense description or title (e.g., "Grocery Shopping", "Electric Bill")
    private String name;

    // Visual icon representation for UI display (emoji or icon class)
    private String icon;

    // Category name for display purposes (e.g., "Food", "Utilities")
    private String categoryName;

    // Category database ID for backend processing and relationships
    private Long categoryId;

    // Expense amount using BigDecimal for precise monetary calculations
    private BigDecimal amount;

    // Date when the expense occurred (without time component)
    private LocalDate date;

    // Timestamp when expense record was created (auto-set by system)
    private LocalDateTime createdAt;

    // Timestamp when expense record was last modified (auto-updated)
    private LocalDateTime updatedAt;
}