package io.equitrack.dto;

import lombok.AllArgsConstructor;    // Lombok: Generates constructor with all fields
import lombok.Builder;              // Lombok: Enables builder pattern for object creation
import lombok.Data;                 // Lombok: Auto-generates getters, setters, toString, equals, hashCode
import lombok.NoArgsConstructor;    // Lombok: Generates empty constructor for JSON deserialization

import java.math.BigDecimal;        // Precise decimal numbers for monetary values
import java.time.LocalDate;         // Date without time (for income date)
import java.time.LocalDateTime;     // Date with time (for audit timestamps)

/**
 * Data Transfer Object for income transactions
 * Represents money inflow operations in the financial system
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class IncomeDTO {

    // Unique database identifier - auto-generated by JPA
    private Long id;

    // Income description or source (e.g., "Salary", "Freelance Work", "Investment")
    private String name;

    // Visual icon representation for UI display (emoji or icon class)
    private String icon;

    // Category name for display purposes (e.g., "Salary", "Business", "Investments")
    private String categoryName;

    private String type = "income";

    // Category database ID for backend processing and relationships
    private Long categoryId;

    // Income amount using BigDecimal for precise monetary calculations
    private BigDecimal amount;

    // Date when the income was received (without time component)
    private LocalDate date;

    // Timestamp when income record was created (auto-set by system)
    private LocalDateTime createdAt;

    // Timestamp when income record was last modified (auto-updated)
    private LocalDateTime updatedAt;
}