package io.equitrack.dto;

import lombok.AllArgsConstructor;    // Lombok: Generates constructor with all fields
import lombok.Builder;              // Lombok: Enables builder pattern for object creation
import lombok.Data;                 // Lombok: Auto-generates getters, setters, toString, equals, hashCode
import lombok.NoArgsConstructor;    // Lombok: Generates empty constructor for JSON deserialization

import java.time.LocalDateTime;     // Date with time (for account creation and update timestamps)

/**
 * Data Transfer Object for user profile information
 * Handles user registration, profile management, and account data
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class ProfileDTO {

    // Unique database identifier - auto-generated by JPA
    private Long id;

    // User's full name for display and personalization
    private String fullName;

    // User's email address - serves as username for login
    private String email;

    // User's password - will be encrypted before storage (never returned in responses)
    private String password;

    // URL to user's profile picture/avatar for personalization
    private String profileImageUrl;

    // Timestamp when user account was created (auto-set by system)
    private LocalDateTime createdAt;

    // Timestamp when user profile was last updated (auto-updated)
    private LocalDateTime updatedAt;
}